spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/telemetry}
    username: ${DATABASE_USERNAME:telemetry}
    password: ${DATABASE_PASSWORD:telemetry}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
