CREATE TABLE telemetry_packet (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    packet_id VARCHAR(255) NOT NULL,
    device_id VARCHAR(255) NOT NULL,
    sequence_number BIGINT NOT NULL,
    altitude DOUBLE PRECISION NOT NULL,
    velocity DOUBLE PRECISION NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_telemetry_packet_packet_id UNIQUE (packet_id)
);

CREATE INDEX idx_telemetry_packet_device_sequence
    ON telemetry_packet (device_id, sequence_number DESC);
